### ISSUE TITLE
Slow Training

### ISSUE THREAD

**Issue by aironaldo** [davidstutz/caffe-tools#1]
I added the augmentation layer to ResNet. Then training speed now is slowed by twice. (Used to be 0.5s per iteration, but now 1s per iteration. Is it normal? Do you know why or do you have solutions?

Thanks.

**Comment by davidstutz** [comment]
Sorry for the really late reply. I guess the main reason is that the data augmentation is implemented in Python. The easiest solution would be an implementation in C++.
